#!/bin/bash

# A stupid shell script for starting erlang with the right libraries;
# there is a probably a better way, but...

CMD=`basename $0`
PRG=$0

while [ -L "${PRG}" ]; do
    ls=`ls -ld "${PRG}"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "${link}" : '\/' > /dev/null; then
        PRG="${link}"
    else
        PRG="`dirname ${PRG}`/${link}"
    fi
done

EVHOME=`dirname "${PRG}"`/..

erl -env MCERLANG_HOME $EVHOME -pa ./ -pa $EVHOME/ebin -pa $EVHOME/Ltl2Buchi/ebin -pa $EVHOME/Ltl2Buchi_glue/ebin -pa $EVHOME/behaviours/ebin -pa $EVHOME/schedulers/ebin -pa $EVHOME/monitors/ebin -pa $EVHOME/stacks/ebin -pa $EVHOME/languages/erlang/ebin -pa $EVHOME/abstractions/ebin -pa $EVHOME/tables/ebin -pa $EVHOME/algorithms/ebin -pa $EVHOME/app/ebin -pa ./ $@ 
