#!/bin/bash

# A script for generating a version number for McErlang

if [ $# -ne 1 ]
then
	echo "Usage: $0 <version>"
	exit 0
fi

Version=$1 
Dir=$PWD
SVNREP=`basename $Dir`
Revision=`(svn log | head -2 | tail -1 | awk '{print $1}' | cut -c 2-) 2> /dev/null`
Date=`date`
Version="McErlang $Version [revision $Revision++ compiled on ${Date}]"
#Version="McErlang $SVNREP:revision $Revision++ compiled on ${Date}"
echo "-module(mce_version)." > src/mce_version.erl
echo "-export([version/0])." >> src/mce_version.erl
echo >> src/mce_version.erl
echo "version() -> " >> src/mce_version.erl
echo -n "  \"">> src/mce_version.erl
echo -n $Version >> src/mce_version.erl
echo "\".">> src/mce_version.erl
(cd src; erlc -o ../ebin mce_version.erl)



